
from langchain_google_genai import ChatGoogleGenerativeAI     # Google Gemini LLM
from langchain_core.prompts import ChatPromptTemplate          # For creating prompt templates
from langchain_core.output_parsers import StrOutputParser      # To clean LLM text output
from langchain.memory import ConversationBufferMemory          # Stores chat history
from dotenv import load_dotenv                                 # Loads GOOGLE_API_KEY from .env file
import json                                                    # For dataset encoding
import asyncio                                                 # Enables async tasks


# ---------------------------------------------------------
# LOAD ENVIRONMENT VARIABLES
# ---------------------------------------------------------
# Loads your GOOGLE_API_KEY from .env file automatically.
# Without this, Gemini will not work.
# ---------------------------------------------------------
load_dotenv()


# ---------------------------------------------------------
# INITIALIZE GEMINI LLM (MAIN BRAIN)
# ---------------------------------------------------------
# convert_system_message_to_human=True helps Gemini understand
# system prompts better (improves accuracy).
# ---------------------------------------------------------
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    convert_system_message_to_human=True
)


# ---------------------------------------------------------
# CONVERSATION MEMORY
# ---------------------------------------------------------
# This stores all previous messages (user + AI)
# so the bot can remember context.
#
# input_key      → name of field for user message
# memory_key     → where memory is saved inside LangChain
# output_key     → name where LLM reply is stored
# return_messages → True means store objects, not plain text
# ---------------------------------------------------------
memory = ConversationBufferMemory(
    input_key="request",
    memory_key="chat_history",
    output_key="response",
    return_messages=True
)


# ---------------------------------------------------------
# SAMPLE MARKS DATASET (used in marks tool)
# ---------------------------------------------------------
# This is not used directly by the bot.
# It is sent to the LLM so it can answer marks questions.
# ---------------------------------------------------------
marks_data = {
    "Alice": {"Math": 95, "Science": 88, "English": 92},
    "Bob":   {"Math": 78, "Science": 85, "English": 80}
}


# ---------------------------------------------------------
# ASYNC TOOLS
# ---------------------------------------------------------
# These are different styles of responses the LLM can generate.
# The router chooses which one to use.
#
# ALL responses are generated by the LLM.
# NOTHING is predefined.
# ---------------------------------------------------------

async def positive_tool(request, chat_history):
    """
    Tool for happy/positive user messages.
    """
    prompt = (
        f"The user sounds happy.\n\n"
        f"User: {request}\n"
        f"Chat history: {chat_history}\n\n"
        f"Reply in a warm, uplifting way."
    )
    result = await llm.ainvoke(prompt)
    return result.content


async def negative_tool(request, chat_history):
    """
    Tool for sad/stressed/angry messages.
    """
    prompt = (
        f"The user seems sad or upset.\n\n"
        f"User: {request}\n"
        f"Chat history: {chat_history}\n\n"
        f"Reply with empathy and emotional comfort."
    )
    result = await llm.ainvoke(prompt)
    return result.content


async def marks_tool(request, chat_history):
    """
    Tool for answering academic marks questions.
    Sends marks JSON to LLM.
    """
    prompt = (
        f"Here is the student marks data:\n"
        f"{json.dumps(marks_data, indent=2)}\n\n"
        f"User question: {request}\n"
        f"Chat history: {chat_history}\n\n"
        f"Answer using the dataset above."
    )
    result = await llm.ainvoke(prompt)
    return result.content


async def suicide_tool_dynamic(request, chat_history):
    """
    Tool for suicidal or self-harm messages.
    Generates safe, supportive LLM response.
    """
    prompt = (
        "The user has expressed thoughts of self-harm.\n"
        "Your reply must:\n"
        "- Be supportive\n"
        "- Encourage reaching out to family/friends\n"
        "- Suggest contacting professionals or a helpline\n"
        "- NEVER encourage self-harm\n\n"
        f"User: {request}\n"
        f"Chat history: {chat_history}"
    )
    result = await llm.ainvoke(prompt)
    return result.content


async def default_tool(request, chat_history):
    """
    General tool for normal conversations.
    """
    prompt = (
        f"General conversation.\n\n"
        f"User: {request}\n"
        f"Chat history: {chat_history}\n\n"
        f"Respond helpfully and naturally."
    )
    result = await llm.ainvoke(prompt)
    return result.content


# ---------------------------------------------------------
# ROUTER (Classifier)
# ---------------------------------------------------------
# This LLM decides which tool to use.
# It returns ONE WORD:
#
#   positive | negative | marks | suicide | default
# ---------------------------------------------------------
router_prompt = ChatPromptTemplate.from_messages([
    ("system", """
        You are an intent classifier.

        Classify the user's message into one category:
        positive / negative / marks / suicide / default

        Output ONLY the word.
    """),
    ("user", "{request}")
])

# String output parser cleans raw output.
router_chain = router_prompt | llm | StrOutputParser()


# ---------------------------------------------------------
# MAIN CHAT AGENT (CALLED BY FastAPI)
# ---------------------------------------------------------
# Steps:
#   1. Load conversation history
#   2. Ask LLM which tool to use
#   3. Run that tool (positive, negative, etc.)
#   4. Save conversation to memory
#   5. Return {"response": ..., "tool_used": ...}
# ---------------------------------------------------------

async def chat_agent(user_input):
    """
    Main function used by FastAPI.
    Generates LLM answer + which tool was used.
    """

    # 1. Load past chat history
    chat_history = memory.load_memory_variables({})["chat_history"]

    # 2. LLM decides the category
    decision_raw = await router_chain.ainvoke({"request": user_input})
    decision = decision_raw.strip().lower().split()[0]

    # 3. Run correct tool
    if decision == "positive":
        llm_response = await positive_tool(user_input, chat_history)
        tool_used = "positive"

    elif decision == "negative":
        llm_response = await negative_tool(user_input, chat_history)
        tool_used = "negative"

    elif decision == "marks":
        llm_response = await marks_tool(user_input, chat_history)
        tool_used = "marks"

    elif decision == "suicide":
        llm_response = await suicide_tool_dynamic(user_input, chat_history)
        tool_used = "suicide"

    else:
        llm_response = await default_tool(user_input, chat_history)
        tool_used = "default"

    # 4. Save this turn in memory (for future context)
    memory.save_context(
        {"request": user_input},
        {"response": llm_response, "tool_used": tool_used}
    )

    # 5. Return final result for FastAPI → frontend
    return {
        "response": llm_response,
        "tool_used": tool_used
    }
